### ISSUE TITLE
SKIP_ROOT_KEYS missing total_connections and curr_connections

### ISSUE THREAD

**Issue by buckleypm** [sensu-plugins/sensu-plugins-twemproxy#2]
https://github.com/sensu-plugins/sensu-plugins-twemproxy/blob/master/bin/metrics-twemproxy.rb#L39
-  SKIP_ROOT_KEYS = %w(service source version uptime timestamp)
-  SKIP_ROOT_KEYS = %w(service source version uptime timestamp total_connections curr_connections)

Which results in a panic happening @ https://github.com/sensu-plugins/sensu-plugins-twemproxy/blob/master/bin/metrics-twemproxy.rb#L78

Due to the value being a FIXNUM.

**Comment by majormoses** [comment]
@buckleypm could you put together a pr for a fix?

**Comment by buckleypm** [comment]
I would love to, but unfortunately all my public code submissions need to go thru corp review. If possible it would be better to have someone else do the actual code change. Appreciate you taking a look at this.

**Comment by majormoses** [comment]
@buckleypm understood, I have limited bandwidth but if I have some time I will look into a fix.

**Comment by majormoses** [comment]
fixed via: https://rubygems.org/gems/sensu-plugins-twemproxy/versions/1.0.1

In addition to the default working now there is a new option to allow them being overwritten at runtime so if you ever hit something similar in the you can unblock yourself while waiting for a plugin update.
